# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AtQuery
                                 A QGIS plugin
 AI Chat forQGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-21
        copyright            : (C) 2025 by AdelaC
        email                : adelacky.de@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AtQuery class from file AtQuery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AtQuery import AtQuery
    return AtQuery(iface)
